# Generated by Django 5.0.6 on 2024-08-02 22:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True,
                max_length=30,
                region=None,
                unique=True,
                verbose_name="Phone Number",
            ),
        ),
    ]
