# Generated by Django 5.0.6 on 2024-08-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="patient",
        ),
        migrations.AddField(
            model_name="appointment",
            name="patients",
            field=models.ManyToManyField(
                related_name="appointments",
                to="patients.patient",
                verbose_name="Patients",
            ),
        ),
    ]
